# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: foo

auth_server:
  url: "https://server.foo.smart-village.app"
  callback_url: "https://rss-importer.foo.smart-village.app/oauth/confirm_access"

target_server:
  url: "https://json.foo.smart-village.app/api"
  __comment: "re-use credetials from auth_server"
# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.

rss_feeds:
  - url: http://smart-village.net/
    data:_type: news
    import:
      intro: false
      body: "encoded"
      external_id: false
      title: "title"
      images: false
    auth:
      key: "foo"
      secret: "bar"
